name: vegetos_flutter
description: Vegetos App in Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  grouped_buttons: ^1.0.4
  pin_view: ^1.0.1
  google_maps_flutter: ^0.5.21+11
  dotted_border: ^1.0.3
  provider: ^3.1.0+1
  http: ^0.12.0+2
  device_info: ^0.4.1+2
  jaguar_jwt: ^2.1.6
  package_info: ^0.4.0+11
  uuid: ^2.0.4
  progress_dialog: ^1.2.0
  shared_preferences: ^0.5.4+8
  fluttertoast: ^3.1.3
  wc_flutter_share: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/splash_logo.png
    - top_pattern.png
    - bottom_pattern.png
    - welcome_top_pattern.png
    - guide_01.png
    - guide_02.png
    - guide_03.png
    - ad01.png
    - ad02.png
    - product01.png
    - product02.png
    - product03.png
    - product04.png
    - product05.png
    - product05.png
    - product06.png
    - about-app.png
    - about-vegetos.png
    - address.png
    - customer_support_menu.png
    - edit-pencil.png
    - home.png
    - logout.png
    - mobile.png
    - my_addressess.png
    - mycart.png
    - myorders.png
    - my_subscription.png
    - offerzone.png
    - rate-us.png
    - share.png
    - shared_cart.png
    - wallet_menu.png
    - vegitables.png
    - fruits.png
    - seasonals.png
    - exotics.png
    - herbs.png
    - search-dashboard.png
    - 01-product.png
    - 02-product.png
    - 03-product.png
    - 04-product.png
    - plus.png
    - minus.png
    - promocode.png
    - wallet.png
    - order_placed.png
    - delivery-location.png
    - search-icon.png
    - close.png
    - current-location.png
    - no-result.png
    - back.png
    - cart.png
    - filter.png
    - Cherry-Tomatoes.png
    - selected-refine.png
    - pomegranate-furit.png
    - tick-orange.png
    - customer-support.png
    - order-placed.png
    - confirmation.png
    - login.png
    - verify.png
    - profile.png
    - whoops.png
    - order-delivered.png
    - order-confirmed.png
    - cancel-subscription.png
    - locate-on-map.png
    - locality-not-found.png
    - offerzone_01.png
    - wallet-bg.png
    - add-balance-wallet.png
    - cashback-wallet.png
    - purchase-wallet.png
    - order-cancelled.png
    - user-not-found-error.png

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/googleSans-medium.ttf
          weight: 500
        - asset: fonts/GoogleSans-bold.ttf
          weight: 700
        - asset: fonts/GoogleSans-regular.ttf
          weight: 400

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
